server:
  port: 8092

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/order-service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/